### ISSUE TITLE
NRE in when measuring text with manually added font since beta16

### ISSUE THREAD

**Issue by loraderon** [SixLabors/Fonts#266]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Fonts
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/Fonts/issues) and [closed](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When measuring (some) manually added fonts, a NullReferenceException is thrown.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SixLabors.Fonts.Tables.AdvancedTypographic.GPosTable.GetFeatureLookups(Tag& stageFeature, ScriptClass script)
   at SixLabors.Fonts.Tables.AdvancedTypographic.GPosTable.TryUpdatePositions(FontMetrics fontMetrics, GlyphPositioningCollection collection, KerningMode kerningMode, Boolean& kerned)
   at SixLabors.Fonts.StreamFontMetrics.UpdatePositions(GlyphPositioningCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.TextLayout.ProcessText(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextLayout.GenerateLayout(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextMeasurer.Measure(String text, TextOptions options)
```

### Steps to Reproduce
Run the provided project. 
Downgrading to 1.0.0-beta15 (and changing `.Add` to `.Install`) resolves the issue.

### System Configuration

- Fonts version: 1.0.0-beta17
- Other Six Labors packages and versions:
- Environment (Operating system, version and so on): Windows 11
- .NET Framework version: .NET 6.0
- Additional information:

[imagesharp-fonts.zip](https://github.com/SixLabors/Fonts/files/8763056/imagesharp-fonts.zip)

**Comment by JimBobSquarePants** [comment]
@loraderon Thanks for providing the font, that makes life MUCH easier! 👍  

Downgrading avoids the issue because that beta didn't have any text shaping functionality. Fix looks simple enough.
