### ISSUE TITLE
Mac error: Invalid glyph format, only TTF glyph outlines supported.

### ISSUE THREAD

**Issue by chorostipico** [SixLabors/Fonts#29]
Trying to get any font from the system collection results in the above error on a Mac. Windows is working fine. e.g.

using System;
using SixLabors.Fonts;

namespace TestSixLaborsFont
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
				FontFamily family = FontCollection.SystemFonts.Find("Arial");
			}
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());    
            }
        }
    }
}

SixLabors.Fonts.Exceptions.InvalidFontFileException: Invalid glyph format, only TTF glyph outlines supported.
   at SixLabors.Fonts.FontReader..ctor(Stream stream, TableLoader loader)
   at SixLabors.Fonts.FontDescription.LoadDescription(String path)
   at SixLabors.Fonts.FileFontInstance..ctor(String path)
   at SixLabors.Fonts.SystemFontCollection.<>c.<.ctor>b__1_3(String x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SixLabors.Fonts.SystemFontCollection..ctor()
   at SixLabors.Fonts.FontCollection.<>c.<.cctor>b__15_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at TestSixLaborsFont.Program.Main(String[] args) in .../TestSixLaborsFont/Program.cs:line 12

**Comment by tocsoft** [comment]
The issue is true type fonts can store glyph outlines a few different ways, TrueType outlines, CFF outlines and even SVG at the moment we only support TrueType outlines. It looks like arial in MacOS is stored with CCF outlines which is the problem however this is a bug in the fact that because its using CCF data would shouldn't be trying to open it and should have skipped it from being loaded by the SystemFonts collections. (Which i'll fix soon.)

Normally I would recommend not using SystemFonts at all and instead the the fonts directly into a custom FontCollection that gives you full control over the exact version of the font and not be dependent of the differences between , not just OSs but OS versions too, as vendors will periodically update the system fonts which could easily break your code.

**Comment by tocsoft** [comment]
looking at the code its potentially not Arial that's at fault, it will actually throw that exception if you have any font file with the *.ttf file extension that incorrectly has CCF outlines in any of the following locations on a mac,

 - ~/Library/Fonts/
 - /Library/Fonts/
 - /Network/Library/Fonts/
 - /System/Library/Fonts/
 - /System Folder/Fonts/

I'll be pushing out an update to prevent it throwing in that was in the future but technically it would happen if you managed to install a similar faulty font file on a windows box too, it doesn't look like its specifically a mac issue.

**Comment by tocsoft** [comment]
sorry totally forgot i needed to do a release for this fix, I've now released this in version 0.1.0-alpha0012
